#!/usr/bin/env sh

sligh --client-output ./react_ui/src/generated-client.ts \
      --server-output ./express_server/define-endpoints.js \
      --model-output ./model.ts \
      --state-transition-properties-output ./state-transition-properties.ts \
      recur.lang